frr defaults traditional
hostname r3
no ipv6 forwarding
!
interface eth1
 ip address 10.0.13.3/24
 ip ospf cost 10
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.34.3/24
 ip ospf cost 10
 ip ospf network point-to-point
!
router ospf
 ospf router-id 3.3.3.3
 network 10.0.13.0/24 area 0
 network 10.0.34.0/24 area 0
 timers throttle spf 50 100 500
!
line vty
!
