frr defaults traditional
hostname r4
no ipv6 forwarding
!
interface eth1
 ip address 10.0.24.4/24
 ip ospf cost 10
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.34.4/24
 ip ospf cost 10
 ip ospf network point-to-point
!
interface eth3
 ip address 10.0.4.1/24
 ip ospf passive
!
interface eth4
 ip address 10.0.5.1/24
 ip ospf passive
!
interface eth5
 ip address 10.0.6.1/24
 ip ospf passive
!
router ospf
 ospf router-id 4.4.4.4
 network 10.0.24.0/24 area 0
 network 10.0.34.0/24 area 0
 network 10.0.4.0/24 area 0
 network 10.0.5.0/24 area 0
 network 10.0.6.0/24 area 0
 timers throttle spf 50 100 500
!
line vty
!
